import serial.tools.list_ports
import numpy as np
import datetime

import pyqtgraph as pg
from pyqtgraph.Qt import QtCore

# ------------------------------- GUI Components -------------------------------
PLOT_VALUES = 100  # Number of values to store and plot

# Create the main GUI app and widget for plotting basic sensor data
sensor_gui = pg.mkQApp("Sensor Data GUI")
basic_widget = pg.GraphicsLayoutWidget(show=True, title="Basic Sensor Data GUI")
basic_widget.resize(1000, 1000)
basic_widget.setWindowTitle("Basic Sensor Data GUI")

# Create the basic accelerometer data plot
acc_plt = basic_widget.addPlot(title="Accelerometer (mg)", row=0, col=0)
acc_plt.addLegend()

# Create the basic gyroscope data plot
gyro_plt = basic_widget.addPlot(title="Gyroscope (mdps)", row=0, col=1)
gyro_plt.addLegend()

# Create the basic magnetometer data plot
mag_plt = basic_widget.addPlot(title="Magnetometer (mgauss)", row=1, col=0)
mag_plt.addLegend()

# Create the basic sun sensor data plot
sun_plt = basic_widget.addPlot(title="Sun sensors", row=1, col=1)
sun_plt.addLegend()

# Create a dictionary for organising the plots for each sensor axis
plot_dict = {"ACC": [acc_plt.plot(pen='r', name="X"),
                     acc_plt.plot(pen='g', name="Y"),
                     acc_plt.plot(pen='b', name="Z")],

             "GRO": [gyro_plt.plot(pen='r', name="X"),
                     gyro_plt.plot(pen='g', name="Y"),
                     gyro_plt.plot(pen='b', name="Z")],

             "MAG": [mag_plt.plot(pen='r', name="X"),
                     mag_plt.plot(pen='g', name="Y"),
                     mag_plt.plot(pen='b', name="Z")],

             "SUN": [sun_plt.plot(pen='c', name="-Z"),
                     sun_plt.plot(pen='b', name="+Z"),
                     sun_plt.plot(pen='r', name="+X"),
                     sun_plt.plot(pen='g', name="+Y"),
                     sun_plt.plot(pen='m', name="-X"),
                     sun_plt.plot(pen='y', name="-Y")]}

# Create data arrays for storing the data for each sensor axis
# NOTE: arr[0] = a sensor's tick array (x-axis)
data_dict = {"ACC": np.zeros((4, PLOT_VALUES)),
             "GRO": np.zeros((4, PLOT_VALUES)),
             "MAG": np.zeros((4, PLOT_VALUES)),
             "SUN": np.zeros((7, PLOT_VALUES))}


# ---------------------------- GUI Update Function -----------------------------
def update():  # Connected to the `timeout()` signal generated by `timer` below
    if board_serial.in_waiting > 0:
        # Write serial data to the log file
        raw_data = board_serial.readline()
        data = raw_data.decode("utf-8")
        log_file.write(data)

        # Process serial data string and extract sensor axis data
        if "|DATA|" in data:
            data = data[7::].strip("\n").split(",")
            data[1] = int(data[1])  # Converts the data tick
            for i in range(2, len(data)):
                data[i] = float(data[i])  # Converts sensor axis data

            # Move all of a sensor's data (tick data & axis data) down by one index
            data_arr = data_dict[data[0]]  # Gets the sensor's data array
            for i in range(PLOT_VALUES - 1):
                data_arr[0][i] = data_arr[0][i + 1]  # Moves down tick data
                for a in range(1, len(data_arr)):
                    data_arr[a][i] = data_arr[a][i + 1]  # Moves down axis data

            # Append a sensor's new data to its data arrays
            plot_arr = plot_dict[data[0]]  # Gets the sensor's plot array
            data_arr[0][PLOT_VALUES - 1] = data[1]  # Appends new tick data
            for a in range(len(data_arr) - 1):
                data_arr[a + 1][PLOT_VALUES - 1] = data[a + 2]  # Appends new axis data
                plot_arr[a].setData(x=data_arr[0], y=data_arr[a + 1])  # Plots new acis data


# -------------------------------- GUI Program ---------------------------------
# Search through available serial ports for the ADCS Integration Board device
ports = serial.tools.list_ports.comports()
for p in ports:
    if "STMicroelectronics STLink Virtual COM Port" in p.description:
        print(f"Found the device: {p.description}\nUsing the port: {p.device}")

        # Create a log file name containing the current date/time
        dt = datetime.datetime.now()
        log_name = f"{dt.day}-{dt.month}-{dt.year}_{dt.hour}{dt.minute}{dt.second}.log"
        print(f"Logging to: {log_name}")

        with open(log_name, "w") as log_file:
            with serial.Serial(p.device, 115200, timeout=1) as board_serial:
                timer = QtCore.QTimer()
                timer.timeout.connect(update)  # Connects the `timer.timeout()` signal to the `update()` slot
                timer.start(1)  # Generates a `timeout()` signal every 1 ms

                if __name__ == "__main__":
                    pg.exec()  # Starts the GUI application
